<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix mb-3">
    <?php echo $this->video(
        [
            'source' => $source,
            'type'   => 'hls',
        ]
    ); ?>
    <?php if (!empty($config['page_title']) || !empty($config['page_description'])) { ?>
        <div class="card mb-3 mt-3">
            <?php if (!empty($config['page_title'])) { ?>
                <div class="card-header bg-transparent">
                    <div class="card-title">
                        <h1><?php echo $config['page_title']; ?></h1>
                    </div>
                </div>
            <?php } ?>
            <?php if (!empty($config['page_description'])) { ?>
                <div class="card-body">
                    <div class="card-text">
                        <?php echo $config['page_description']; ?>
                    </div>
                </div>
            <?php } ?>
        </div>
    <?php } ?>
</div>